import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "../components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}  >
        <div className="sm:font-[family-name:var(--font-geist-sans)]  w-full">
          <div className="bg-gradient-to-br from-gray-700 via-black to-stone-700 flex flex-1 items-center h-full justify-center">
            <div className="min-h-screen  flex flex-col items-center justify-center p-4">
              <div className="max-w-md w-full space-y-8">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
